import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";
import React from "react";

const Home: NextPage = () => {
  const [data, setData] = React.useState<string[]>([]);
  const $fileInput = React.useRef<HTMLInputElement>(null);
  const uploadImage = api.example.uploadImage.useMutation({
    onSuccess: async (data, variables) => {
      await Promise.all(
        data.map((url, index) =>
          fetch(url, {
            method: "PUT",
            body: variables[index]!,
          })
        )
      );

      setData(variables);
    },
  });

  const getImages = api.example.getImages.useQuery(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input ref={$fileInput} type="text" />
        <p>Type file names separated by comma</p>
        <br />
        <button
          onClick={(event) => {
            event.preventDefault();
            if (!$fileInput.current) {
              return;
            }
            const value = $fileInput.current.value;
            const fileNames = value.split(",");
            uploadImage.mutate(fileNames);
          }}
        >
          Get upload urls
        </button>

        <p>Urls</p>
        <pre>
          {getImages.data?.map((url) => (
            <React.Fragment key={url.url}>
              <strong>{url.name}</strong>
              <br />
              <span>{url.url}</span>
              <br />
              <br />
            </React.Fragment>
          ))}
        </pre>
      </main>
    </>
  );
};

export default Home;
